// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'headerList': string;
  'main': string;
  'moreInfo': string;
  'pageHeader': string;
  'stepDescription': string;
}
export const cssExports: CssExports;
export default cssExports;
