// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'logout': string;
  'rightContent': string;
  'split': string;
}
export const cssExports: CssExports;
export default cssExports;
