// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cards': string;
  'container': string;
  'content': string;
  'createBtn': string;
  'form': string;
  'groupBtn': string;
  'header': string;
  'pagination': string;
}
export const cssExports: CssExports;
export default cssExports;
