// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'materialListContainer': string;
  'search': string;
  'tabs': string;
}
export const cssExports: CssExports;
export default cssExports;
