// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'anticon': string;
  'expanded': string;
  'hasExpandTag': string;
  'tagSelect': string;
  'trigger': string;
}
export const cssExports: CssExports;
export default cssExports;
