// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'avatarList': string;
  'card': string;
  'cardItemContent': string;
  'cardList': string;
  'coverCardList': string;
}
export const cssExports: CssExports;
export default cssExports;
