// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'anticon': string;
  'card': string;
  'editable': string;
  'errorField': string;
  'errorIcon': string;
  'errorListItem': string;
  'errorPopover': string;
}
export const cssExports: CssExports;
export default cssExports;
