// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'avatarHolder': string;
  'detail': string;
  'name': string;
  'tabsCard': string;
  'tags': string;
  'tagsTitle': string;
  'team': string;
  'teamTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
