// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'content': string;
  'createBtn': string;
  'header': string;
  'pagination': string;
  'tabs': string;
}
export const cssExports: CssExports;
export default cssExports;
