// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'error': string;
  'getCaptcha': string;
  'login': string;
  'main': string;
  'password': string;
  'progress': string;
  'progress-pass': string;
  'submit': string;
  'success': string;
  'warning': string;
}
export const cssExports: CssExports;
export default cssExports;
