// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'listItemExtra': string;
  'listItemMetaTitle': string;
  'selfTrigger': string;
}
export const cssExports: CssExports;
export default cssExports;
