// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'editor': string;
  'editorBd': string;
  'editorContent': string;
  'editorHd': string;
  'editorSidebar': string;
  'flow': string;
  'koni': string;
  'mind': string;
}
export const cssExports: CssExports;
export default cssExports;
