// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'avatarItem': string;
  'avatarItemLarge': string;
  'avatarItemMini': string;
  'avatarItemSmall': string;
  'avatarList': string;
}
export const cssExports: CssExports;
export default cssExports;
