// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'label': string;
  'standardFormRow': string;
  'standardFormRowBlock': string;
  'standardFormRowGrid': string;
  'standardFormRowLast': string;
}
export const cssExports: CssExports;
export default cssExports;
