// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'card': string;
  'cardAvatar': string;
  'cardDescription': string;
  'cardList': string;
  'contentLink': string;
  'extraImg': string;
  'item': string;
  'newButton': string;
  'pageHeaderContent': string;
}
export const cssExports: CssExports;
export default cssExports;
