// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'area_code': string;
  'avatar': string;
  'avatar_title': string;
  'baseView': string;
  'button_view': string;
  'left': string;
  'phone_number': string;
  'right': string;
}
export const cssExports: CssExports;
export default cssExports;
