// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'extraContentSearch': string;
  'formResult': string;
  'headerInfo': string;
  'listCard': string;
  'listContent': string;
  'listContentItem': string;
  'standardList': string;
  'standardListForm': string;
}
export const cssExports: CssExports;
export default cssExports;
