// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'leftMenu': string;
  'main': string;
  'right': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
